version: '3.9'

services:
  database:
    image: mysql:latest
    restart: always
    volumes:
      - ../../data/nextcloud/database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Usr@dm1n
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=ncmgr
      - MYSQL_PASSWORD=Te@rr@str0

  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin:latest
    restart: always
    ports:
      - '8000:80'

  server:
    image: nextcloud:latest
    restart: always
    volumes:
      - ../../data/nextcloud/server:/var/www/html
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=ncmgr
      - MYSQL_PASSWORD=Te@rr@str0
      - MYSQL_HOST=database
      - NEXTCLOUD_ADMIN_USER=manager
      - NEXTCLOUD_ADMIN_PASSWORD=Usrm@n@g3r
      - NEXTCLOUD_TRUSTED_DOMAINS='localhost, 172.16.0.*'
    depends_on:
      - database
    ports:
      - '80:80'

volumes:
  database: {}
  server: {}
