version: '3.9'

services:
  database:
    image: mariadb:latest
    restart: always
    volumes:
      - ../../data/nextcloud/database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=p@ssw0rd
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=p@ssw0rd

  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin:latest
    restart: always
    ports:
      - '8000:80'

  server:
    image: nextcloud:latest
    restart: always
    volumes:
      - ../../data/nextcloud/server:/var/www/html
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=p@ssw0rd
      - MYSQL_HOST=database
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=p@ssw0rd
      - NEXTCLOUD_TRUSTED_DOMAINS='localhost'
    depends_on:
      - database
    ports:
      - '80:80'

volumes:
  database: {}
  server: {}
