version: '3.9'

services:
  database:
    image: mysql:latest
    restart: always
    volumes:
      - ../../data/nextcloud/database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud

  server:
    image: nextcloud:latest
    restart: always
    volumes:
      - ../../data/nextcloud/server:/var/www/html
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_HOST=database
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=nextcloud
      - NEXTCLOUD_TRUSTED_DOMAINS='localhost'
    depends_on:
      - database
    ports:
      - '80:80'

volumes:
  database: {}
  server: {}
