version: "3.9"
    
services:
  database:
    image: mariadb:latest
    volumes:
      - ../../data/wordpress/database:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    
  server:
    depends_on:
      - database
    image: wordpress:latest
    volumes:
      - ../../data/wordpress/server:/var/www/html
    ports:
      - '80:80'
    restart: always
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
volumes:
  database: {}
  server: {}
